//! Read/write a reusable gitatlas config file (TOML).
//!
//! `gen-config` writes a fully-commented `[options]` table (every option at its
//! default, each with an inline explanation) plus a `[[committer]]` block per
//! committer in the repo (editable display `label` and `image` path). `--config`
//! loads it: `[options]` become the base config (CLI flags still override), and
//! committer entries supply per-author labels and avatar images.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::Deserialize;

use crate::config::Config;
use crate::ingest::History;

#[derive(Deserialize, Default)]
struct ConfigFile {
    #[serde(default)]
    options: Config,
    #[serde(default)]
    committer: Vec<Committer>,
}

#[derive(Deserialize, Default, Clone)]
struct Committer {
    #[serde(rename = "match", default)]
    match_key: String,
    #[serde(default)]
    name: String,
    #[serde(default)]
    label: String,
    #[serde(default)]
    image: String,
}

/// Result of loading a config file.
pub struct Loaded {
    pub options: Config,
    /// key (lowercased email or name) -> display label.
    pub labels: HashMap<String, String>,
    /// key (lowercased email or name) -> avatar image path.
    pub images: HashMap<String, PathBuf>,
}

pub fn load(path: &Path) -> Result<Loaded> {
    let text = std::fs::read_to_string(path)
        .with_context(|| format!("reading config file {}", path.display()))?;
    let cf: ConfigFile =
        toml::from_str(&text).with_context(|| format!("parsing config file {}", path.display()))?;
    let base = path.parent().map(|p| p.to_path_buf()).unwrap_or_default();

    let mut labels = HashMap::new();
    let mut images = HashMap::new();
    for c in &cf.committer {
        let mut keys = vec![c.match_key.trim().to_lowercase()];
        if !c.name.trim().is_empty() {
            keys.push(c.name.trim().to_lowercase());
        }
        let label = if c.label.trim().is_empty() {
            c.name.clone()
        } else {
            c.label.clone()
        };
        for k in keys {
            if k.is_empty() {
                continue;
            }
            if !label.trim().is_empty() {
                labels.insert(k.clone(), label.clone());
            }
            if !c.image.trim().is_empty() {
                let mut p = PathBuf::from(c.image.trim());
                if p.is_relative() {
                    p = base.join(&p);
                }
                images.insert(k, p);
            }
        }
    }

    Ok(Loaded {
        options: cf.options,
        labels,
        images,
    })
}

/// Apply CLI-provided options over a base config: any field whose CLI value
/// differs from the compiled default is treated as explicitly set and wins.
pub fn merge_cli_over(base: &Config, cli: &Config) -> Result<Config> {
    let def = Config::default();
    let v_cli = toml::Value::try_from(cli)?;
    let v_def = toml::Value::try_from(&def)?;
    let mut v_base = toml::Value::try_from(base)?;
    if let (Some(tc), Some(td), Some(tb)) =
        (v_cli.as_table(), v_def.as_table(), v_base.as_table_mut())
    {
        for (k, vc) in tc {
            if td.get(k) != Some(vc) {
                tb.insert(k.clone(), vc.clone());
            }
        }
        // Fields present in default but absent in cli's table are Options that
        // are None on the CLI; leave whatever the base had.
    }
    v_base.try_into().context("merging config")
}

/// Generate a fully-commented config file for `history`, with all options at the
/// values in `d` and one committer block per author.
pub fn generate(d: &Config, history: &History) -> String {
    let mut s = String::new();
    s.push_str("# gitatlas config — generated by `gitatlas gen-config`.\n");
    s.push_str("# Edit the options and fill in committer `label`/`image`, then render with:\n");
    s.push_str("#   gitatlas --config gitatlas.toml <repo>\n");
    s.push_str("# CLI flags override values set here. Lines starting with '#' are unset.\n\n");

    s.push_str("[options]\n\n");

    s.push_str("# --- Git & input ---\n");
    line(
        &mut s,
        &format!("rev = {:?}", d.rev),
        "revision / branch to walk",
    );
    comment(
        &mut s,
        "since = \"2020-01-01\"",
        "only commits after this date",
    );
    comment(
        &mut s,
        "until = \"2024-01-01\"",
        "only commits before this date",
    );
    line(
        &mut s,
        &format!("max_commits = {}", d.max_commits),
        "most recent N commits (0 = all)",
    );
    line(
        &mut s,
        &format!("first_parent = {}", d.first_parent),
        "first-parent mainline only (false = full history)",
    );
    line(
        &mut s,
        &format!("submodules = {}", d.submodules),
        "include git submodules as tiles",
    );
    line(
        &mut s,
        "submodule_include = []",
        "only these submodules (name/path/substring)",
    );
    line(&mut s, "submodule_exclude = []", "exclude these submodules");

    s.push_str("\n# --- Files & folders (path globs vs the repo-relative path) ---\n");
    line(
        &mut s,
        "include = []",
        "only these files, e.g. [\"src/**\", \"**/*.rs\"]",
    );
    line(
        &mut s,
        "exclude = []",
        "drop these files, e.g. [\"**/tests/**\", \"vendor/**\"]",
    );

    s.push_str("\n# --- Output & timing ---\n");
    line(
        &mut s,
        &format!("out = {:?}", d.out.to_string_lossy()),
        "output file (repo is passed on the CLI)",
    );
    line(&mut s, &format!("codec = {:?}", codec_str(d)), "mp4 | webm");
    line(
        &mut s,
        &format!("quality = {:?}", quality_str(d)),
        "draft | balanced | high",
    );
    line(
        &mut s,
        &format!("width = {}", d.width),
        "frame width in px (even)",
    );
    line(
        &mut s,
        &format!("height = {}", d.height),
        "frame height in px (even)",
    );
    line(&mut s, &format!("fps = {}", d.fps), "frames per second");
    line(
        &mut s,
        &format!("seconds = {:?}", d.seconds.unwrap_or(60.0)),
        "target length in seconds",
    );
    comment(
        &mut s,
        "seconds_per_commit = 0.4",
        "screen time per commit (overrides seconds)",
    );
    line(
        &mut s,
        &format!("max_frames = {}", d.max_frames),
        "hard cap on frames (0 = none)",
    );
    line(
        &mut s,
        &format!("threads = {}", d.threads),
        "worker threads (0 = all cores)",
    );

    s.push_str("\n# --- Layout ---\n");
    line(
        &mut s,
        &format!("max_depth = {}", d.max_depth),
        "max folder depth (0 = unlimited)",
    );
    line(
        &mut s,
        &format!("depth_mode = {:?}", depthmode_str(d)),
        "omit | collapse (items beyond max_depth)",
    );
    line(
        &mut s,
        &format!("gamma = {:?}", d.gamma),
        "area gamma 0.3..1.0 (lower = flatter sizes)",
    );
    comment(
        &mut s,
        "size_cap = 4000.0",
        "fixed area cap in lines (default: auto 95th pct)",
    );
    line(
        &mut s,
        &format!("min_open_px = {:?}", d.min_open_px),
        "folders smaller than this (px) collapse",
    );
    line(
        &mut s,
        &format!("pad = {:?}", d.pad),
        "padding inside folders (px)",
    );
    line(
        &mut s,
        &format!("margin = {:?}", d.margin),
        "outer margin (px)",
    );
    line(
        &mut s,
        &format!("saturation = {:?}", d.saturation),
        "border color saturation 0..1",
    );
    line(
        &mut s,
        &format!(
            "background = [{}, {}, {}]",
            d.background[0], d.background[1], d.background[2]
        ),
        "background RGB 0-255",
    );

    s.push_str("\n# --- Tiles & minimap ---\n");
    line(
        &mut s,
        &format!("show_minimap = {}", d.show_minimap),
        "minimap lines inside file tiles",
    );
    line(
        &mut s,
        &format!("minimap_line_gap = {:?}", d.minimap_line_gap),
        "gap between minimap lines (px)",
    );
    line(
        &mut s,
        &format!("minimap_max_lines = {}", d.minimap_max_lines),
        "max minimap lines per tile",
    );
    line(
        &mut s,
        &format!("border = {}", d.border),
        "draw tile borders",
    );
    line(
        &mut s,
        &format!("border_width = {:?}", d.border_width),
        "border width (px)",
    );

    s.push_str("\n# --- Labels ---\n");
    line(
        &mut s,
        &format!("show_dir_names = {}", d.show_dir_names),
        "show folder names",
    );
    line(
        &mut s,
        &format!("dir_name_max_depth = {}", d.dir_name_max_depth),
        "label folders up to this depth",
    );
    line(
        &mut s,
        &format!("show_file_names = {}", d.show_file_names),
        "show file names on large tiles",
    );
    line(
        &mut s,
        &format!("file_name_min_px = {:?}", d.file_name_min_px),
        "min tile width (px) to draw a file name",
    );
    line(
        &mut s,
        &format!("label_size = {:?}", d.label_size),
        "label font size (px)",
    );

    s.push_str("\n# --- Avatars & beams ---\n");
    line(
        &mut s,
        &format!("show_avatars = {}", d.show_avatars),
        "show committer avatars",
    );
    line(
        &mut s,
        &format!("show_avatar_names = {}", d.show_avatar_names),
        "show names beneath avatars",
    );
    line(
        &mut s,
        &format!("avatar_size = {}", d.avatar_size),
        "avatar diameter (px)",
    );
    comment(
        &mut s,
        "avatar_config = \"avatars.conf\"",
        "extra name/email=image file (the [[committer]] blocks below usually suffice)",
    );
    comment(
        &mut s,
        "avatar_dir = \"avatars/\"",
        "directory of images named by name/email",
    );
    line(
        &mut s,
        &format!("gravatar = {}", d.gravatar),
        "download gravatars (needs network)",
    );
    line(
        &mut s,
        &format!("gravatar_timeout_ms = {}", d.gravatar_timeout_ms),
        "gravatar timeout (ms)",
    );
    line(
        &mut s,
        &format!("show_beams = {}", d.show_beams),
        "beams from avatars to changed files",
    );
    line(
        &mut s,
        &format!("beam_intensity = {:?}", d.beam_intensity),
        "beam glow multiplier",
    );

    s.push_str("\n# --- Animation ---\n");
    line(
        &mut s,
        &format!("transition = {:?}", d.transition),
        "morph fraction per commit (smooth mode)",
    );
    line(
        &mut s,
        &format!("highlight_seconds = {:?}", d.highlight_seconds),
        "how long a changed tile glows (s)",
    );
    line(
        &mut s,
        &format!("avatar_idle_seconds = {:?}", d.avatar_idle_seconds),
        "avatar fades after this idle time (s)",
    );

    s.push_str("\n# --- HUD ---\n");
    line(
        &mut s,
        &format!("show_hud = {}", d.show_hud),
        "top meta bar",
    );
    line(&mut s, &format!("show_date = {}", d.show_date), "show date");
    line(
        &mut s,
        &format!("show_author = {}", d.show_author),
        "show author + subject",
    );
    line(
        &mut s,
        &format!("show_progress = {}", d.show_progress),
        "show progress bar",
    );
    line(
        &mut s,
        &format!("show_langs = {}", d.show_langs),
        "show language split",
    );
    comment(
        &mut s,
        "title = \"My Project\"",
        "title at the top-left of the meta bar",
    );

    s.push_str("\n# --- Misc ---\n");
    line(
        &mut s,
        &format!("cache = {}", d.cache),
        "use the on-disk history cache",
    );

    // Committers.
    s.push_str("\n# =============================== Committers ===============================\n");
    s.push_str("# One [[committer]] block per person. What each field does:\n");
    s.push_str("#\n");
    s.push_str("#   match  Ties this block to commits — the committer's git email (or name).\n");
    s.push_str("#          Leave it as generated unless several emails belong to one person,\n");
    s.push_str("#          in which case point it at whichever email/name you want to match.\n");
    s.push_str("#   name   The committer's REAL git name, straight from the repo. It is here\n");
    s.push_str("#          for reference (so you know who this block is) and also helps match.\n");
    s.push_str("#          You normally do NOT change this.\n");
    s.push_str("#   label  The name shown ON SCREEN (under the avatar and in the HUD author\n");
    s.push_str("#          line). >>> This is the field you EDIT to rename someone. <<<\n");
    s.push_str("#          If you leave it empty, it falls back to `name`.\n");
    s.push_str("#   image  Path to a picture for their avatar (absolute, or relative to THIS\n");
    s.push_str("#          file). Leave \"\" to keep the auto-generated icon.\n");
    s.push_str("#\n");
    s.push_str("# Example — same person, shown on screen as \"Ada\" with a custom picture:\n");
    s.push_str("#   [[committer]]\n");
    s.push_str("#   match = \"ada@example.com\"   # matched by this email\n");
    s.push_str("#   name  = \"Ada Lovelace\"      # real git name (unchanged)\n");
    s.push_str("#   label = \"Ada\"               # <- appears on screen\n");
    s.push_str("#   image = \"avatars/ada.png\"   # <- their avatar\n");
    s.push_str("# ========================================================================\n\n");

    let mut authors: Vec<&crate::ingest::Author> = history.authors.iter().collect();
    authors.sort_by_key(|a| a.name.to_lowercase());
    for a in authors {
        let key = if a.email.trim().is_empty() {
            a.name.clone()
        } else {
            a.email.clone()
        };
        s.push_str("[[committer]]\n");
        s.push_str(&format!("match = {}\n", toml_str(&key)));
        s.push_str(&format!("name  = {}\n", toml_str(&a.name)));
        s.push_str(&format!("label = {}\n", toml_str(&a.name)));
        s.push_str("image = \"\"\n\n");
    }

    s
}

fn line(s: &mut String, kv: &str, comment: &str) {
    // pad key=value to a column, then append the comment.
    let col = 30;
    if kv.len() < col {
        s.push_str(kv);
        for _ in kv.len()..col {
            s.push(' ');
        }
    } else {
        s.push_str(kv);
        s.push(' ');
    }
    s.push_str("# ");
    s.push_str(comment);
    s.push('\n');
}

fn comment(s: &mut String, kv: &str, c: &str) {
    let text = format!("# {kv}");
    let col = 30;
    if text.len() < col {
        s.push_str(&text);
        for _ in text.len()..col {
            s.push(' ');
        }
    } else {
        s.push_str(&text);
        s.push(' ');
    }
    s.push_str("# ");
    s.push_str(c);
    s.push('\n');
}

/// Encode a string as a valid TOML basic string. Printable Unicode (including
/// emoji / variation selectors) is emitted literally; only `"`, `\` and control
/// characters are escaped (Rust's `{:?}` escapes e.g. U+FE0F, which TOML rejects).
fn toml_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '\u{08}' => out.push_str("\\b"),
            '\u{0c}' => out.push_str("\\f"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04X}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn codec_str(d: &Config) -> &'static str {
    match d.codec {
        crate::config::Codec::Mp4 => "mp4",
        crate::config::Codec::Webm => "webm",
    }
}
fn quality_str(d: &Config) -> &'static str {
    match d.quality {
        crate::config::Quality::Draft => "draft",
        crate::config::Quality::Balanced => "balanced",
        crate::config::Quality::High => "high",
    }
}
fn depthmode_str(d: &Config) -> &'static str {
    match d.depth_mode {
        crate::config::DepthMode::Omit => "omit",
        crate::config::DepthMode::Collapse => "collapse",
    }
}
